# Generated by Django 4.2.11 on 2024-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_rooms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(),
        ),
    ]
