# Generated by Django 4.2.11 on 2024-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_rooms_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='wifi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
