# Generated by Django 4.2.11 on 2024-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
                ('des', models.TextField(max_length=100)),
                ('ac', models.BooleanField()),
                ('roomtype', models.CharField(max_length=100)),
                ('bedtype', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='static/img')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
