# Generated by Django 4.2.11 on 2024-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='addroom',
            name='rno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
