# Generated by Django 4.2.11 on 2024-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_alter_addroom_rno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='rno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
