# Generated by Django 4.2.11 on 2024-06-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_alter_addroom_rno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='room',
        ),
    ]
